### ISSUE TITLE
Do we have to guess the context where a symbol came from?

### ISSUE THREAD

**Issue by emanguy** [ftomassetti/java-symbol-solver#6]
I've been looking through your example and JavaParserFacade.java. It looks like JavaParserFacade can only resolve types for the TypeSolver you pass to JavaParserFacade.get(). If that's the case, what's the point of JavaParserFacade storing multiple TypeSolvers? For example, if a class imported 3 other classes from different packages it seems I'd have to do this:

```java
public void solveSymbolInClass()
{
    // Do some parsing, hit symbol s. Assume it's a descendent of Node and could possibly come from package1, package2, or package3
    // Make type solvers for the three packages
    JavaParserTypeSolver solverP1 = new JavaParser("src/package1/");
    JavaParserTypeSolver solverP2 = new JavaParser("src/package2/");
    JavaParserTypeSolver solverP3 = new JavaParser("src/package3");
    
    // Build a JavaParserFacade to find type for node s
    JavaParserFacade resolver = new JavaParserFacade(solverP1);
    resolver.get(solverP1).getType(s); // This may or may not get resolved
    resolver.get(solverP2).getType(s); // This may or may not get resolved
    resolver.get(solverP3).getType(s); // This may or may not get resolved
}
```

or this:

```java
public void solveSymbolInClass()
{
    // Do some parsing, hit symbol s. Assume it's a descendent of Node and could possibly come from package1, package2, or package3
    // Make type solvers for the three packages
    JavaParserTypeSolver solverP1 = new JavaParser("src/package1/");
    JavaParserTypeSolver solverP2 = new JavaParser("src/package2/");
    JavaParserTypeSolver solverP3 = new JavaParser("src/package3");

    // Make a combined type solver for all 3 packages
    CombinedTypeSolver cts = new CombinedTypeSolver();
    cts.add(solverP1);
    cts.add(solverP2);
    cts.add(solverP3);
    
    // Build a JavaParserFacade to find type for node s
    JavaParserFacade resolver = new JavaParserFacade(cts);
    resolver.get(cts).getType(s);
}
```

Why is the get() function necessary?

**Comment by ftomassetti** [comment]
Hi, first of all thank you for your interest in this project.

The symbol solver needs just to know what classpath you are using when compiling a project because it is the same classpath used to resolve the symbols. So you need to tell to it:
* all jars you are using
* all source directories you are using

You can then combine them using  a CombinedTypeSolver.
So you would not need one different JavaParserTypeSolver for each package but just one for the root of the source directory. For example:

So not this:
```
    JavaParserTypeSolver solverP1 = new JavaParser("src/package1/");
    JavaParserTypeSolver solverP2 = new JavaParser("src/package2/");
    JavaParserTypeSolver solverP3 = new JavaParser("src/package3");
```
but just this:
```
    JavaParserTypeSolver solver = new JavaParserTypeSolver("src/");
```

The TypeSolver then should be created once for the whole project, you do not need to create one for each source file considering the imports of that file.

The method get of JavaParserFacade give you an instance of JavaParserFacade and uses a cache so that if you pass to it the same type solver it will give you back the same JavaParserFacade instead of instantiating a new one.

This project has still a very poor documentation so please feel free to ask as many questions as you need and also send me examples of what you are trying to do and I would be happy to help and possibly improve the documentation.

**Comment by emanguy** [comment]
Okay. I think I'm just confused about how JavaParserFacade fits into all this. I feel it it would make more sense to just use some CombinedTypeSolver.getType(Node) function rather than going through JavaParserFacade. What is this object's purpose?

**Comment by emanguy** [comment]
Also, you're saying that JavaParserSymbolSolver traverses the file tree recursively?

**Comment by ftomassetti** [comment]
well, the TypeSolver has only the ability to resolve fully qualified names. So if you ask to it the definition of java.util.List it will find it for you.

JavaParserFacade on the other end look at the AST and knows the rules which affects symbol resolution. For example if you refer to List it will look if it can find a class named List locally, if not it will look if there is a class named List in the same package or if you have imported it. It will do the necessary call to the TypeSolver also.

The JavaParserTypeSolver build a list of types defined in source code.

**Comment by emanguy** [comment]
Okay, last question. Let's say I used the JavaParserFacade.solve() function on a MethodCallExpr and I wanted to visit the result with a class derived from VoidVisitorAdapter. How would I go about extracting the com.github.javaparser.ast.body.MethodDeclaration object from the resulting me.tomassetti.symbolsolver.model.declarations.MethodDeclaration that I retrieve from the returned SymbolReference?

**Comment by emanguy** [comment]
Is this even possible?

**Comment by ftomassetti** [comment]
Currently it is not possible because I did not think of it as something users would be interested into but it would be trivial to do: if the method resolved corresponds to a node obtainted from JavaParser it will be a JavaParserMethodDeclaration and it will contain the Node. We should just add a method to return it.
However it could be also a method obtained through reflection (this is the case for methods declared in Object) or through Javassist (used to examine JARs). So you would have to check the concrete class and cast it from MethodDeclaration to JavaParserMethodDeclaration.

**Comment by emanguy** [comment]
Okay, I'll fork your project and make a pull request. I'll add a ```.getNode()``` function to all the classes in ```me.tomassetti.symbolsolver.javaparsermodel.declarations```.

**Comment by ftomassetti** [comment]
It sounds great! Thanks
